name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clone the GitHub repository on the machite
      uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install program dependencies
      run: npm install

    - name: Start frontend
      run: npm run start-fe &

    - name: Replace the backend endpoint
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js

    - name: Start Backend
      run: npm run start-be &

    - name: Install Browsers
      run: npx playwright install                                              

    - name: Run integration tests
      run: npm run test:ui

  deploy-fe:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Deploy Frontend
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID_FE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true

  deploy-be:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Deploy Backend
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID_BE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true