name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clone the GitHub repository on the machite
      uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install program dependencies
      run: npm ci

    - name: Start frontend
      run: npm run start &

    - name: Start server
      run: npm run server &

    - name: Wait for frontend to be ready
      run: |
        curl --silent --fail --max-time 60 http://localhost:3000 || exit 1

    - name: Wait for backend to be ready
      run: |
        curl --silent --fail --max-time 60 http://localhost:5000 || exit 1

    - name: Run integration tests
      run: npm test
