name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clone the GitHub repository on the machite
      uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install program dependencies
      run: npm ci

    - name: Install Playwright dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          curl \
          gnupg \
          lsb-release \
          sudo \
          ca-certificates
        npx playwright install-deps

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run integration tests
      run: npm test
